### ISSUE TITLE
Fix officer profile exception

### ISSUE THREAD

**Issue by sea-kelp** [OrcaCollective/OpenOversight#384]
```
web_1           | 2023-11-12 06:38:46,920 INFO sqlalchemy.engine.Engine [generated in 0.00029s] {'param_1': 848}                                                                       
web_1           | [2023-11-12 06:38:46,924] ERROR in views: Error finding officer                                                                                                      
web_1           | Traceback (most recent call last):                                                                                                                                   
web_1           |   File "/usr/src/app/OpenOversight/app/main/views.py", line 313, in officer_profile                                                                                  web_1           |     officer.incidents.query.order_by(Incident.date.desc(), Incident.time.desc())                                                                                     web_1           |     ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                          
web_1           | AttributeError: 'InstrumentedList' object has no attribute 'query'
```

**Comment by sea-kelp** [comment]
Related to https://github.com/lucyparsons/OpenOversight/pull/1056, might be because we're on SQLAlchemy 2.x

**Comment by sea-kelp** [comment]
Reproduced the issue upstream:
```
web_1       | 2023-11-12 07:42:48,046 INFO sqlalchemy.engine.Engine [generated in 0.00029s] {'param_1': 40}                                                                            web_1       | [2023-11-12 07:42:48,050] ERROR in views: Error finding officer: <class 'AttributeError'> 'InstrumentedList' object has no attribute 'query' Traceback (most recent call 
last):                                                                                                                                                                                 
web_1       |   File "/usr/src/app/OpenOversight/app/main/views.py", line 315, in officer_profile               
web_1       |     officer.incidents.query.order_by(Incident.date.desc(), Incident.time.desc())                                                                                         
web_1       |     ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                              web_1       | AttributeError: 'InstrumentedList' object has no attribute 'query'
```
